### ISSUE TITLE
user-can-create-an-entry

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/week-planner#1]
## 💰 Motivation

Coders will want to plan out their week so they can code as often as possible

## 📐 Plan

Create a responsive form that allows users to store notes into a table 

## 🖼️ Wireframes

TBD

## ✅ Task List

- [x] Add clickable boxes containing weekday names
- [x] Query the dom and update window hash on weekday clicks
- [x] Add a form
- [x] Add selections for the day of the week and time
- [x] Add a text area for a description
- [x] Listen for a `'click'` event on add entry and confirm
   - [x] Show entry modal on add entry click 
- [x] Listen for `'submit'` events on the planner entry form and:
   - [x] Put the form's input values into a new object.
   - [x] Add the `nextEntryId` to the object.
   - [x] Increment the `nextEntryId` on the data model.
   - [x] Reset the form inputs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
